language: python
python:
  - 2.6
  - 2.7
cache:
  - bugzilla
install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential g++ graphviz libapache2-mod-perl2 libdaemon-generic-perl libssl-dev perlmagick pkg-config unzip
  - sudo apt-get -y install libchart-perl libclass-dbi-mysql-perl libemail-mime-perl libemail-send-perl libgd-perl libgd-graph-perl liblist-moreutils-perl libtimedate-perl libdigest-sha-perl libtemplate-perl liburi-perl libxml-twig-perl
  - git clone --branch production --depth 10 https://git.mozilla.org/webtools/bmo/bugzilla.git bugzilla
  - pip install -r requirements.txt
before_script:
  - cd bugzilla; ./install-module.pl --all
script: python setup.py develop && py.test tests
