language: python
python:
  - 2.6
  - 2.7
cache:
  - bugzilla
install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential g++ graphviz libapache2-mod-perl2 libdaemon-generic-perl libgd2-xpm-dev libssl-dev perlmagick pkg-config unzip
  - git clone --branch production --depth 10 https://git.mozilla.org/webtools/bmo/bugzilla.git bugzilla
  - pip install -r requirements.txt
before_scipt:
  - cd bugzilla; ./install-module.pl --all
script: python setup.py develop && py.test tests
